# Generated by Django 5.2.8 on 2025-11-16 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254700000000'", regex='^\\+?254?\\d{9,12}$')])),
                ('address', models.TextField()),
                ('service_type', models.CharField(choices=[('antenatal', 'Antenatal Care & Follow-Up'), ('consultations', 'Consultations'), ('partner_health', 'Partner Health Support'), ('postpartum', 'Postpartum Care & Follow-Up'), ('preconception', 'Preconception Care'), ('labor_prep', 'Preparation for Labor & Delivery'), ('teenage', 'Teenage Empowerment & Reproductive Education')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('weeks_pregnant', models.IntegerField(blank=True, null=True)),
                ('previous_pregnancies', models.CharField(blank=True, max_length=255)),
                ('medical_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254700000000'", regex='^\\+?254?\\d{9,12}$')])),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('new-patient', 'New Patient Consultation'), ('prenatal', 'Prenatal Care Question'), ('postpartum', 'Postpartum Support'), ('general', 'General Inquiry')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General Enquiry',
                'verbose_name_plural': 'General Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
